services:
  news-inspector:
    image: mmaksymko/news-inspector:1.0.2
    container_name: news-inspector
    volumes:
      - inspector_data:/app/data
      - ~/cache/huggingface:/root/.cache/huggingface
    env_file:
      - .env
      - .env.local
    restart: unless-stopped

volumes:
  inspector_data: