name: Manual Docker Build & Push with Cache
run-name: Build ${{ github.event.inputs.docker_tag }}

on:
  workflow_dispatch:
    inputs:
      docker_tag:
        description: 'Docker tag to apply (e.g. v1.0.0, staging, my-feature-build)'
        required: true

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # By default, this will check out the exact commit/branch that 
        # triggered the workflow_dispatch. You can omit "with: ref" entirely.
        #
        # If you’d rather be explicit, you can replace the above with:
        #
        # with:
        #   ref: ${{ github.ref }}

      # 2) Set up Docker Buildx (enables BuildKit + caching)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3) Log in to Docker Hub using repository secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4) Build & Push, with registry-backed cache
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile

          # Tell Buildx to pull cache layers from this specific tag
          cache-from: type=registry,ref=your-dockerhub-username/your-repo:cache

          # After building, push updated cache layers back here
          cache-to: type=registry,ref=your-dockerhub-username/your-repo:cache,mode=max

          push: true

          # Tag the built image exactly as the user entered
          tags: |
            mmaksymko/news-inspector:${{ github.event.inputs.docker_tag }}
